Feature/player ranking
Frank-Schaeske/ScoutingHelper pull request #31
Opened 2023-08-09 13:44 UTC by Frank-Schaeske

2023-08-09 15:05 UTC, FelineHuhn requested changes
Great progress Frank 🎉 
I left you some suggestions below.

2023-08-09 15:05 UTC, FelineHuhn commented on pages/players/[id]/ranking.js
> +    mutate,
```suggestion

```
I think you don't use this, or?

2023-08-10 09:03 UTC, Frank-Schaeske commented
Thanks for your review, Feline! I've adapted my code accordingly.

2023-08-10 09:31 UTC, Kheirah approved these changes
Your changes look good!

I left some comments for further improvements. You can choose to ignore them if you want to move on.

2023-08-10 09:31 UTC, Kheirah commented on components/Ranking/index.js
> +  if (!isReady || isLoading || error)
The `isReady` property of the `router` object should be used in `useEffect`.

I'd say, if you experience errors, you might want to add one such `useEffect` and check the value of `isReady` within the callback. If you're not seeing any errors, you may leave the code as is.

2023-08-10 09:31 UTC, Kheirah commented on components/Ranking/index.js
> +`;
For cleaner code, you might want to put the styled components into their own file.

2023-08-10 09:31 UTC, Kheirah commented on pages/players/[id]/ranking.js
> +  if (!isReady || isLoading || error)
The same is true here (`useEffect` in case you experience errors related to `isReady`).

2023-08-10 09:31 UTC, Kheirah commented on pages/players/[id]/ranking.js
> +`;
Same thing here as well, create a new file for the styles if you want to get leaner.

2023-08-10 10:09 UTC, Frank-Schaeske commented
Thanks for your suggestions, new style files are definitely on my to-do list after this US.

2023-08-10 10:41 UTC, merged